### ISSUE TITLE
Excluded Paths not working

### ISSUE THREAD

**Issue by S-n-d** [cooltronicpl/varnishcache#1]
Hello,

Thank you for this great plugin! 👍  Really helps speeding up a website.

I'm trying to exclude a contact page because it contains a form. Because I guess caching and CSRF tokens don't match well? I put in **_contact_** in the excluded paths list, but when I look at the stats it is still being cached. Any idea why this exclusion is not working?

Craft 4.4.15
Plugin 2.3.0

**Comment by cooltronicpl** [comment]
Try to exclude: 
`/contact/`
or
`/contact`

**Comment by owc-afernandez** [comment]
Hi,

Love this plugin! 

Really helping to speed up our website, but having issues with cached search return files.

Have tried adding following excluded paths, but plugin is still creating file for 'search/results'

/search/*
/search/results
/search/results/
/search/results/*

**plugin enabled** 
![Screenshot 2023-07-25 at 1 40 02 PM](https://github.com/cooltronicpl/varnishcache/assets/140210309/c79a50ac-7bd9-4476-b166-ccb46ee9e438)

**plugin disabled**
![Screenshot 2023-07-25 at 1 20 32 PM](https://github.com/cooltronicpl/varnishcache/assets/140210309/42179e5c-223f-4479-a78f-b41f0aa2f8b8)

**Comment by cooltronicpl** [comment]
Do you try REGEX?:
```/search/(.*)```
