### ISSUE TITLE
Unkown method on newest Craft version

### ISSUE THREAD

**Issue by ferventdigital** [cooltronicpl/varnishcache#2]
When using this plugin on the newest Craft version (5.4.6) it shows a unknown method getIsSystemOn() error, as it was replaced with getIsLive() in Craft

**Comment by cooltronicpl** [comment]
Hi @ferventdigital. Can you test our `3.1.0` version? We made minor changes discovered locally and pushed them into `3.0.0`. Does everything work as before the Craft update?

**Comment by ferventdigital** [comment]
We can't reproduce the issue anymore, thanks!
